version: "2"
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mytest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    container_name: postgres
